# H2 data source and console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

# hibernate logging
logging.level.org.hibernate=error
spring.jpa.show-sql=true

spring.application.name=election-backend
app.frontend.url=http://localhost:5173

#server.port=8081
#
#election.frontend.url=http://localhost:5173
#
#logging.level.root=info