# H2 data source and console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:electiondb
spring.datasource.username=sam
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# hibernate logging
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.application.name=election-backend
app.frontend.url=http://localhost:5173

#server.port=8081
#
#election.frontend.url=http://localhost:5173
#
#logging.level.root=info