-- QUIZ
INSERT INTO quiz (id, title) VALUES (1, 'Verkiezingsquiz');

-- QUESTIONS
INSERT INTO question (id, text, quiz_id) VALUES (1, 'De belastingen voor de rijken moeten omhoog.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (2, 'Er moet meer in onderwijs worden geïnvesteerd.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (3, 'Nederland moet meer vluchtelingen toelaten.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (4, 'Moet er een minimumleeftijdsgrens van 15 jaar worden ingesteld voor social media?', 1);
INSERT INTO question (id, text, quiz_id) VALUES (5, 'Abortus moet uit het Wetboek van Strafrecht', 1);
INSERT INTO question (id, text, quiz_id) VALUES (6, 'De hoeveelheid vee in Nederland moet minstens de helft omlaag', 1);
INSERT INTO question (id, text, quiz_id) VALUES (7, 'Illegaal verblijf in Nederland moet strafbaar worden', 1);
INSERT INTO question (id, text, quiz_id) VALUES (8, 'Psychisch lijden mag geen reden zijn voor euthanasie', 1);
INSERT INTO question (id, text, quiz_id) VALUES (9, 'Er moet meer geld naar het openbaar vervoer, ook als daardoor minder geld overblijft voor wegen.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (10, 'Het moet makkelijker worden om je geslacht in je geboorteakte te veranderen.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (11, 'Er moet meer geld worden uitgegeven aan jeugdzorg, ook als de belastingen hierdoor stijgen.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (12, 'Voor het eenmalig gebruik van plastic betaal je extra. Die heffing moet verdwijnen.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (13, 'Sociale media apps moeten stoppen met het gebruik van verslavende algoritmes.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (14, 'Alle schoolboeken en benodigdheden gratis (ook mbo/hbo/uni).', 1);
INSERT INTO question (id, text, quiz_id) VALUES (15, 'Verbieden van dieren in kleine kooien (legbatterijen).', 1);
INSERT INTO question (id, text, quiz_id) VALUES (16, 'De overheid moet burgers en bedrijven meer vrijheid geven.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (17, 'Nederland moet meer samenwerken met de Europese Unie.', 1);
INSERT INTO question (id, text, quiz_id) VALUES (18, 'De overheid moet huurwoningen voor jongeren goedkoper maken.', 1);

-- PARTY POSITIONS FOR QUESTION 1
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEUTRAAL', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEUTRAAL', 1);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEUTRAAL', 1);

-- PARTY POSITIONS FOR QUESTION 2
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEUTRAAL', 2);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEUTRAAL', 2);

-- PARTY POSITIONS FOR QUESTION 3
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEUTRAAL', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEUTRAAL', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 3);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 3);

-- PARTY POSITIONS FOR QUESTION 4
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 4);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 4);

-- PARTY POSITIONS FOR QUESTION 5
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'JA', 5);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'JA', 5);

-- PARTY POSITIONS FOR QUESTION 6
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 6);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 6);

-- PARTY POSITIONS FOR QUESTION 7
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 7);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'JA', 7);

-- PARTY POSITIONS FOR QUESTION 8
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEUTRAAL', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'JA', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEUTRAAL', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 8);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 8);

-- PARTY POSITIONS FOR QUESTION 9
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 9);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 9);

-- PARTY POSITIONS FOR QUESTION 10
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'JA', 10);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'JA', 10);

-- PARTY POSITIONS FOR QUESTION 11
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 11);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 11);

-- PARTY POSITIONS FOR QUESTION 12
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'NEE', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'NEE', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEE', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'NEE', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'JA', 12);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'JA', 12);

-- PARTY POSITIONS FOR QUESTION 13
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEUTRAAL', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'NEUTRAAL', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'NEE', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 13);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 13);

-- PARTY POSITIONS FOR QUESTION 14
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEUTRAAL', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEUTRAAL', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 14);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 14);

-- PARTY POSITIONS FOR QUESTION 15
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'NEUTRAAL', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 15);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 15);

-- PARTY POSITIONS FOR QUESTION 16
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'NEUTRAAL', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEUTRAAL', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEUTRAAL', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'JA', 16);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'JA', 16);

-- PARTY POSITIONS FOR QUESTION 17
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'NEUTRAAL', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'NEUTRAAL', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'NEUTRAAL', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 17);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 17);

-- PARTY POSITIONS FOR QUESTION 18
INSERT INTO party_position (party, position, question_id) VALUES ('VVD', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('GroenLinks-PvdA', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('D66', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('PVV', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('CDA', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('FvD', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('BIJ1', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('PvdD', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('ChristenUnie', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('SP', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('50Plus', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('DENK', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('FNP', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrede voor Dieren', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('JA21', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('Volt', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('SGP', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('BBB', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('NSC', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('BVNL', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('LP', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('PiratenPartij', 'JA', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('Vrij Verbond', 'NEE', 18);
INSERT INTO party_position (party, position, question_id) VALUES ('De Linie', 'NEE', 18);
